remote_theme: eecs485staff/primer-spec
plugins:
    - jekyll-remote-theme
    - jekyll-optional-front-matter
    - jekyll-readme-index
    - jekyll-relative-links
    - jemoji
kramdown:
    input: GFM
readme_index:
    remove_originals: true
    with_frontmatter: true

title: Engineering 100-980
description: "Homepage of UMich ENGR 100-980: Rocket Science"